# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/AIShiftScheduler_KE4',
                'doc_host': 'https://kobus78.github.io',
                'git_url': 'https://github.com/kobus78/AIShiftScheduler_KE4',
                'lib_path': 'AIShiftScheduler_KE4'},
  'syms': { 'AIShiftScheduler_KE4.core': { 'AIShiftScheduler_KE4.core.foo': ('core.html#foo', 'AIShiftScheduler_KE4/core.py'),
                                           'AIShiftScheduler_KE4.core.say_hello': ('core.html#say_hello', 'AIShiftScheduler_KE4/core.py')}}}
